title: "Umer Khan"
description: "Personal site of Umer Khan – AI undergrad exploring code, Linux, and ideas."
url: "https://umerkn.me"
baseurl: ""

author:
  name: "Umer Khan"
  email: "hi@umerkn.me"

theme_color: "#ffffff"

markdown: kramdown
highlighter: rouge

permalink: /blog/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /projects/:path/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

include:
  - projects/gpa-calculator

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
