title: "Umer Khan"
description: "AI student and developer exploring artificial intelligence, code, Linux, and innovative solutions. Building projects with React, Node.js, and modern technologies."
url: "https://umerkniazi.dev"
baseurl: ""

author:
  name: "Umer Khan"
  email: "hello@umerkniazi.dev"

keywords: "Umer Khan, AI Student, Developer, Artificial Intelligence, React, Node.js, JavaScript, TypeScript, Portfolio, Machine Learning, Linux"
twitter_username: "umerkniazi"
github_username: "umerkniazi"
linkedin_username: "umerkniazi"
image: "/assets/images/og-image.jpg"
lang: "en_US"

theme_color: "#ffffff"

markdown: kramdown
highlighter: rouge

permalink: /blog/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  projects:
    output: true
    permalink: /projects/:path/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
